export const measureLabels = {
  'emp'          : 'Beginning-of-Quarter Employment: Counts',
  'empend'       : 'End-of-Quarter Employment: Counts',
  'emps'         : 'Full-Quarter Employment (Stable): Counts',
  'empspv'       : 'Full-Quarter Employment in the Previous Quarter: Counts',
  'emptotal'     : 'Employment - Reference Quarter: Counts',
  'hira'         : 'Hires All: Counts (Accessions)',
  'hirn'         : 'Hires New: Counts',
  'hirr'         : 'Hires Recalls: Counts',
  'sep'          : 'Separations: Counts',
  'hiraend'      : 'End-of-Quarter Hires',
  'hiraendr'     : 'End-of-Quarter Hiring Rate',
  'sepbeg'       : 'Beginning-of-Quarter Separations',
  'sepbegr'      : 'Beginning-of-Quarter Separation Rate',
  'hiras'        : 'Hires All (Stable): Counts (Flows into Full-Quarter Employment)',
  'hirns'        : 'Hires New (Stable): Counts (New Hires to Full-Quarter Status)',
  'seps'         : 'Separations (Stable): Counts (Flow out of Full-Quarter Employment)',
  'sepsnx'       : 'Separations (Stable): Next Quarter: Counts (Flow out of Full-Quarter Employment)',
  'turnovrs'     : 'Turnover (Stable)',
  'frmjbgn'      : 'Firm Job Gains: Counts (Job Creation)',
  'frmjbls'      : 'Firm Job Loss: Counts (Job Destruction)',
  'frmjbc'       : 'Firm Job Change: Net Change',
  'hiraendrepl'  : 'Replacement Hires',
  'hiraendreplr' : 'Replacement Hiring Rate',
  'frmjbgns'     : 'Firm Job Gains (Stable): Counts',
  'frmjblss'     : 'Firm Job Loss (Stable): Counts',
  'frmjbcs'      : 'Job Change (Stable): Net Change',
  'earns'        : 'Full Quarter Employment (Stable): Average Monthly Earnings',
  'earnbeg'      : 'Beginning-of-Quarter Employment: Average Monthly Earnings',
  'earnhiras'    : 'Hires All (Stable): Average Monthly Earnings',
  'earnhirns'    : 'Hires New (Stable): Average Monthly Earnings',
  'earnseps'     : 'Separations (Stable): Average Monthly Earnings',
  'payroll'      : 'Total Quarterly Payroll: Sum',
}

export default measureLabels
