let categoryNames = {
  combinedcomposite: 'Combined',
  densitycomposite: 'Density',
  fluiditycomposite: 'Fluidity',
  diversitycomposite: 'Diversity',
  densitynewfirms: 'New Firms per 1k Pop',
  densityshareofemploymentinnewfirms: '% Emp in New Firms',
  densityshareemp: '% Emp in New Firms',
  densityshareEmpNoAccRet: "% emp in non retail and accomodation sectors",
  densityshareEmpHighTech: "% emp in high tech sector",
  densityshareempqwi_exceptaccomandretail: "% emp in non retail and accomodation sectors",
  densityshareempqwi_hightech: "% emp in high tech sector",
  diversityincomebasedonchildhood: 'Equality of Opportunity',
  diversityopportunity: 'Equality of Opportunity',
  diversitypercentageofforeignbornpopulation: '% Foreign Born',
  diversityforeignborn: '% Foreign Born',
  diversityemploymentlocationquotientvariance: 'Variance of Emp Location Quotient',
  diversityemplqvariance: 'Variance of Emp Location Quotient',
  diversityemploymenthhi: 'Employment Hirschman-Herfindahl Index',
  diversityemphhi: 'Employment Hirschman-Herfindahl Index',
  fluidityhighgrowthfirms: 'High Growth Firms',
  fluidityhighgrowth: 'High Growth Firms',
  fluiditynetmigration: 'Net Migration',
  fluiditytotalmigration: 'Total Migration',
  fluidityinflowmigration: 'Inflow Migration',
  fluidityoutflowmigration: 'Outflow Migration',
  fluidityannualchurn: 'Employee Churn',
  fluiditychurn: 'Employee Churn'
}

export default categoryNames
