let categoryText =  {
	'combined' : ['The EEI represents the overall health of entrepreneurial ecosystems. The EEI is a composite index based on sub-indicators - Fluidity, Density and Diversity - and calculated using various economic and demographic datasets. These sub-indicators are measures of ecosystem health, including population flux, sector variance, worker churn, immigration, and equality of opportunity. In the Entrepreneurial Ecosystem Atlas, every metropolitan statistical area (MSA) in the United States is given an EEI score, and subsequently ranked. Click on the sub-indicator or on the MSAs for further in-depth analysis.'], 

	'density' : ['At the core of any entrepreneurial ecosystem are the entrepreneurs themselves. Density is a measure of the rate entrepreneurs form new firms. The density metric does not measure pure volume, instead it ranks the relative density of new firms and the percentage of the workforce employed by these young firms.','The Density metric is comprised of three measurements: New and young firms per 1k population, share of employment in new and young firms, and high-tech sector density.'],

	'fluidity': ['Fluidity is a measure of the health of an entrepreneurial ecosystems that shows how metropolitan areas re-sort, adapt, and react. The fluidity metric measures population growth, population flux, and worker churn. Taken together these measures show the health of worker reallocation which can improve the quality of matches between workers and jobs and is an important element to regional growth. Barriers to worker reallocation can drag down a region’s entrepreneurial vibrancy. '],

	'diversity': [
				 'A vibrant entrepreneurial ecosystem requires diversity of economy and population. It is important that all parts of the population are engaged in the economy and social mobility is one of the drivers of multi-level engagement.  As such one measure of a diverse entrepreneurial ecosystem is the equality of opportunity which is measured here as cross generational income growth based on parent’s income.',
				 'Healthy ecosystems also attract and assimilate immigrants. Immigrants are historically highly entrepreneurial, starting businesses at a high rate.',
				 'The diversity metric is comprised of two measures: immigration, and income mobility.  An ecosystem that is diverse in these ways tends to be robust and multi-leveled.'
				],

	'newfirms':['New Firms per 1K Population is calculated using the Business Dynamics Statistics Dataset where firm-age is 1 year or less. This number is then divided by the US Census population for the metropolitan area for a given year. For Metropolitan Statistical Areas with changing boundaries, we’ve used the sum of the population of counties in the appropriate geography. Business Dynamics Statistics is the only public dataset that offers both the number of establishments and their firm-age but does not link firms to industry type.'],
	'shareofemploymentinnewfirms':['Share of Employment in New Firms is calculated using Quarterly Workforce Indicators (QWI). During the development of this tool we calculated this metric using both the Business Dynamics Statistics and Quarterly Workforce Indicators datasets and found that the two have only very slight differences. In the final implementation of the tool we chose to use QWI because it is updated more frequently.'],
	'shareEmpNoAccRet':['Share of Employment in New Traded is calculated using Quarterly Workforce Indicators (QWI).  One of the greatest strengths of QWI is that it shows share of employment by both 2-digit NAICS industry and firm-age. This metric calculates share of employment in new firms (<1 year old) in all industries except for retail (NAICS 44-45) and accommodations and food services (NAICS 72).'],
	'shareEmpHighTech':['Share of Employment in High Tech is calculated using Quarterly Workforce Indicators (QWI).  One of the greatest strengths of QWI is that it shows share of employment by both 2-digit NAICS industry and firm-age.This metric calculate share of employment in new firms (<1 year old), only in the sectors Information (NAICS 51) and Professional Scientific and Technical Services (54). '],
	'highgrowthfirms':['The High Growth Firms metric is scored using Inc 5,000 dataset listing the 5,000 fastest growing firms in America. This metric takes into account both the total number of High Growth Firms in a Metropolitan Statistical Area and the number of High Growth Firms per 1K population.'],	
	'netmigration':['Net Migration is taken from the IRS population dataset. This metric is the number of immigrant (incoming) as a percentage of total population minus the number of emigrants (outgoing) as a percentage of total population.'],
	'totalmigration':['Total Migration is taken from the IRS population dataset. This metric is the number of immigrant (incoming) as a percentage of total population minus the number of emigrants (outgoing) as a percentage of total population.'],
	'annualchurn':['Annual Churn is calculated using Quarterly Workforce Indicators. This metric is the employment turnover rate as a percentage of total employment. Annual Churn is the percentage of people who left their job and found new work in a given year. A strong Entrepreneurial Ecosystem has high worker reallocation which can improve the quality of matches between workers and jobs.'],
	'opportunity':['Equality of Opportunity score is calculated using data from the Equality of Opportunity Project. To create an overall metric for metropolitan areas we take the average income change for children whose parents are in the bottom 25th percentile of income and children whose parents in the top 25th percentile of income. This measures how an entrepreneurial ecosystem diversifies opportunity.'],
	'foreignborn':['Percentage of Foreign Born Population is taken from the American Communities Survey of the US Census. Historically, immigrants have a high entrepreneurial propensity.'],
	'emplqvariance':['Economic Diversity is calculated using the Quarterly Census of Earnings and Wages (QCEW). This metric starts by taking the location quotients of four-digit NAICS industries in a metropolitan area and calculates the statistical variance of those values. This is a measure of the Economic Diversity of a Metropolitan Statistical Area, where MSAs with high variance among industries tend to be over specialized. More advanced Metropolitan Economies tend to have lower variance scores. '],
	'emphhi':['The Hirschman-Herfindahl Index (HHI) is calculated using the Quarterly Census of Earnings and Wages (QCEW). This metric starts by taking the employment shares from all four-digit NAICS industries in a metropolitan area and calculates the HHI using those. This is a measure of how specialized an economy is, where MSAs with a high HHI tend to be over-specialized.']	
}

export default categoryText
